version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@MsSql12345
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets

