version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU17-ubuntu-20.04
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@MsSql12345
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    networks:
      - stack_network

  tools:
    image: mcr.microsoft.com/mssql-tools
    container_name: tools
    stdin_open: true
    tty: true
    networks:
      - stack_network

networks:
  stack_network:
