CREATE TABLE EMPLOYEE (
	Empno CHAR(4) NOT NULL, 
	Empname VARCHAR(20) NOT NULL, 
	EmpAddress VARCHAR(20) NOT NULL, 
	Hiredate DATETIME NOT NULL, 
	Position VARCHAR(15) NOT NULL, 
	Salary INT NOT NULL, Skil VARCHAR(50), 
	CONSTRAINT EMPLOYEE_Empno_PK PRIMARY KEY (Empno), 
	CONSTRAINT EMPLOYEE_Empname_UK UNIQUE (Empname) 
)

CREATE TABLE DEPARTMENT (
	Depno CHAR(2) NOT NULL, 
	Depname VARCHAR(15) NOT NULL, 
	DepLocation VARCHAR(15) NOT NULL, 
	CONSTRAINT DEPARTMENT_Depno_PK PRIMARY KEY (Depno) 
)

CREATE TABLE CUSTOMER (
	Custno CHAR(4) NOT NULL, 
	Custname VARCHAR(20) NOT NULL, 
	CusAddress VARCHAR(30) NOT NULL, 
	Telno CHAR(13) NOT NULL, 
	CONSTRAINT CUSTOMER_Custno_PK PRIMARY KEY (Custno) 
)


CREATE TABLE ORDERS (
 Orderno CHAR(4) NOT NULL, 
 orderdate DATETIME NOT NULL, 
 CONSTRAINT ORDERS_Orderno_PK PRIMARY KEY (Orderno) 
)

CREATE TABLE PRODUCT (
	Prodno CHAR(2) NOT NULL, 
	Prodname VARCHAR(15) NOT NULL, 
	Cost INT NOT NULL, Balance INT NOT NULL, 
	CONSTRAINT PRODUCT_Prodno_PK PRIMARY KEY (Prodno) 
)

CREATE TABLE ORDERITEM (
	Orderno CHAR(4) NOT NULL, 
	Prodno CHAR(2) NOT NULL, 
	Orderqty INT NOT NULL, 
	Orderprice INT NOT NULL, 
	CONSTRAINT ORDERITEM_Orderno_PK PRIMARY KEY (Orderno) 
)

CREATE TABLE SUPPLIER (
	Sno CHAR(2) NOT NULL, 
	Sname VARCHAR(20) NOT NULL, 
	Adderess VARCHAR(30) NOT NULL, 
	telno CHAR(13) NOT NULL, 
	CONSTRAINT SUPPLIER_Sno_PK PRIMARY KEY (Sno)
)

CREATE TABLE DEPENDENT (
	Empno CHAR(4) NOT NULL, 
	Dependent_name VARCHAR(20) NOT NULL, 
	relation VARCHAR(15) NOT NULL, CONSTRAINT DEPENDENT_Dependent_name_PK PRIMARY KEY (Dependent_name) 
)

CREATE TABLE CUSTOMER_TYPE (
	Cust_type CHAR(5) NOT NULL, 
	Discount_rate INT NOT NULL, 
	CONSTRAINT CUSTOMER_TYPE_Cust_type_PK PRIMARY KEY (Cust_type) 
)
